config/routes.rb
DataStore::Application.routes.draw do
  resources :time_chunks

  resources :users

  resources :datapoints

end

app/models/time_chunk.rb
class TimeChunk
  attr_accessor :source_id, :date_time, :hash, :db, :errors

  def initialize(attributes = {})
    @source_id  = attributes[:source_id]
    @date_time = attributes[:date_time]
    @hash = attributes[:hash]
    @db = attributes[:db]
    @errors = attributes[:errors]
  end

  def dynamo
  	dynamo_db = AWS::DynamoDB.new
    table = dynamo_db.tables.create('my-table', 10, 5)
    #sleep 1 while table.status
    return table.status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/datapoints_controller.rb
class DatapointsController < ApplicationController
	
	# GET /datapoints
  	# GET /datapoints.json
	def index
		# connect to DB
		db = AWS::DynamoDB.new
		table = db.tables['hive_data_store']
		table.hash_key = [:hive_id, :string]
		table.range_key = [:date_time, :number]

		# initialize data array
		datapoints = []

		# request a maximum of 10 items from Amazon DynamoDB
		table.items.select(:limit => 10).each do |item_data|
			datapoints.push(item_data.attributes)
		end
		
		# pass datapoints to /index
		@var = datapoints
	end

	# POST /datapoints
  	# POST /datapoints.json
	def create
		# connect to DB
		db = AWS::DynamoDB.new
		table = db.tables['hive_data_store']
		table.hash_key = [:hive_id, :string]
		table.range_key = [:date_time, :number]

		# initialize batch
		batch = AWS::DynamoDB::BatchWrite.new

		# batch test
		/batch.put(table, [
			{:hive_id => 'HID100', :date_time => 2322323232, :color => 'green'}
		])
		batch.process!/

		@dataset = params[:value]

		@parsed_json = ActiveSupport::JSON.decode(@dataset)

		my_id = @parsed_json["hive_id"];
		my_time = @parsed_json["date_time"];

		@parsed_json["data"].each do |datapoint|
			dataHash = Hash[:hive_id => my_id, :date_time => my_time];
			datapoint.each_pair do |k,v|
				dataHash.merge!(k => v);
			end
			my_time = my_time -1;
			File.open('test.txt', 'a') {|f| f.write(batch.inspect)};
			thisa = Array.new();
			thisa.push(dataHash)
			batch.put(table, [dataHash]);
		end
		batch.process!


		/@dataset[:datapoints].each do |datapoint|
			@data = {
						:hive_id => @dataset[:id], 
						:date_time => @dataset[:datetime],
						:voltage => @dataset[:voltage],
						:fxpoint => datapoint
					}
			batch.put(table, @data)
			File.open('test.txt', 'a') {|f| f.write(@data) }
		end

		batch.process!/

		#File.open('test.txt', 'a') {|f| f.write(@parsed_json["data"]) }

		
	
	end

	def show
		@body = File.open("test.txt", "rb") {|io| io.read}
	end

end

app/controllers/time_chunks_controller.rb
class TimeChunksController < ApplicationController

  $data_table = "hive_data_store"

  # GET /time_chunks
  # GET /time_chunks.json
  def index
    redirect_to "http://ww.google.com"
    #@time_chunks =  $data_table #TimeChunk.all

    ##respond_to do |format|
      #format.html # index.html.erb
      #format.json { render json: @time_chunks }
    #end
  end

  # GET /time_chunks/1
  # GET /time_chunks/1.json
  def show
    @time_chunk = #TimeChunk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_chunk }
    end
  end

  # GET /time_chunks/new
  # GET /time_chunks/new.json
  def new
    #@time_chunk = TimeChunk.new

    data_set = []
    date_time = Time.now
    
    params[:datapoints].each do |point|
      h = {:hive_id => 'my_id', :date_time => 123}
      point[:params].each {|key, value| h[key] = value}
      data_set.push(h)
    end

    @Batch_Hash = data_set

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_chunk }
    end
  end

  # GET /time_chunks/1/edit
  def edit
    #@time_chunk = #TimeChunk.find(params[:id])
  end

  # POST /time_chunks
  # POST /time_chunks.json
  def create
    data_set = []
    date_time = Time.now
    
    params[:datapoints].each do |point|
      h = {:hive_id => 'my_id', :date_time => 123}
      point[:params].each {|key, value| h[key] = value}
      data_set.push(h)
    end

    @Batch_Hash = data_set

  end

  # PUT /time_chunks/1
  # PUT /time_chunks/1.json
  def update
    @time_chunk = #TimeChunk.find(params[:id])

    respond_to do |format|
      if @time_chunk.update_attributes(params[:time_chunk])
        format.html { redirect_to @time_chunk, notice: 'Time chunk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_chunks/1
  # DELETE /time_chunks/1.json
  def destroy
    @time_chunk = #TimeChunk.find(params[:id])
    @time_chunk.destroy

    respond_to do |format|
      format.html { redirect_to time_chunks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datapoints_helper.rb
module DatapointsHelper
end

app/helpers/time_chunks_helper.rb
module TimeChunksHelper
end

app/views/datapoints/create.html.erb
<%= @params %>

app/views/datapoints/index.html.erb
Hello World, this is the index!
<% @var.each do |i| %>
<br/>
<%= i %>
<% end %>

<%= form_tag(:html => {:'data-type' => 'json'})  do %>
<%= text_field_tag(:value) %>
<%= submit_tag("POST") %>
<% end %>

app/views/datapoints/show.html.erb
<%= @body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/time_chunks/_form.html.erb
<%= form_tag do %>
   <%= label_tag(:q, "Input JSON:") %>
  <%= text_field_tag(:json) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/time_chunks/create.html.erb
<h1><%= @params %></h1>

app/views/time_chunks/edit.html.erb
<h1>Editing time_chunk</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_chunk %> |
<%= link_to 'Back', time_chunks_path %>

app/views/time_chunks/index.html.erb
<h1><%= @time_chunks %></h1>

<table>
  <tr>
    <th>Source</th>
    <th>Date time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>

<br />

app/views/time_chunks/new.html.erb
<h1>New time_chunk</h1>

<%= render 'form' %>

<%= @Batch_Hash %>

<%= link_to 'Back', time_chunks_path %>

app/views/time_chunks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source:</b>
  <%= @time_chunk.source_id %>
</p>

<p>
  <b>Date time:</b>
  <%= @time_chunk.date_time %>
</p>


<%= link_to 'Edit', edit_time_chunk_path(@time_chunk) %> |
<%= link_to 'Back', time_chunks_path %>